social media follow icons
bsi-software/bsi-cx-design-standard-library-web pull request #136
Opened 2024-11-05 10:30 UTC by Ivory-Heartbeat

Ticket: 400541

Die ausgeblendeten social media icons werden im editor jetzt mit einer geringeren Deckungskraft angezeigt, sodass diese visuell als ausgeblendet erkannt werden können.

Außerdem habe ich den Twitterlink ersetzt sowie im Code die Klassen und Variablen die noch mit twitter bezeichnet wurden durch x ersetzt.

Das führt dazu, dass wir ebenfalls einen Change im Mastertemplate machen müssen. (Pull request folgt)

2024-11-05 10:42 UTC, derB4 requested changes
Kannst du auch noch Social-Media-Share anpassen?
Oder haben wir da kein Twitter?

2024-11-05 10:42 UTC, derB4 commented on content-elements/base/social-media-follow/prototype/styles.scss
> +      opacity: 0.3;
das mit dem [data-bsi-remove-if] find ich bisschen beunruhigend - wir benutzen das auch woanders.
Kann man das auf die .hidden-Klasse ändern?

2024-11-05 10:42 UTC, derB4 commented on content-elements/base/social-media-follow/prototype/template.twig
> +    {% set followXURL = (XURL ?: properties.followXURL) ?: "https://www.x.com/" %}
Das ist nicht backwards-kompaktibel.
Was hälst du von: `XURL ?: properties.followXURL ?: properties.followTwitterURL ?: "https://www.x.com/"` ?

2024-11-05 10:42 UTC, derB4 commented on content-elements/base/social-media-follow/prototype/template.twig
> +    {% set followXHidden = (XHidden ?: properties.followXHidden) ?: false %}
same

2024-11-05 11:30 UTC, Ivory-Heartbeat commented on content-elements/base/social-media-follow/prototype/template.twig
> +    {% set followXURL = (XURL ?: properties.followXURL) ?: "https://www.x.com/" %}
Das ist eine gute Idee, ich passe das an.

2024-11-06 10:29 UTC, Ivory-Heartbeat commented
Ich habe alles soweit angepasst.

2024-11-19 13:15 UTC, derB4 approved these changes

2024-11-19 13:19 UTC, merged