Add dark mode in the standard library
bsi-software/bsi-cx-design-standard-library-web pull request #146
Opened 2024-12-02 10:40 UTC by antoninodelfiume

2024-12-02 13:53 UTC, LukasBSI commented
@antoninodelfiume could you update changelog? :)

2025-02-12 15:57 UTC, LukasBSI requested changes

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/index.js
> +  elementLabel = 'Advanced logo',
```suggestion
  elementLabel = 'Logo',
```

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/index.js
> +  elementLabel = 'Advanced logo',
Also add element description:
"Dark- & Light-Mode"

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/index.js
> +  textLmPartLabel = 'Logo light mode',
```suggestion
  textLmPartLabel = 'Logo Light Mode',
```

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/index.js
> +  textDmPartLabel = 'Logo dark mode'
```suggestion
  textDmPartLabel = 'Logo Dark Mode'
```

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/styles.scss
> +      margin-bottom: 0px;
For 0 values always use 0 instead of 0px.
It's technically the same, but we want to stay consistent.

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/advanced/logo-with-darkmode/prototype/styles.scss
> +      bottom: 0px;
```suggestion
      bottom: 0;
```

2025-02-12 15:57 UTC, LukasBSI commented on content-elements/form/poll/prototype/poll.js
> +    let name = "bsi-poll-radios-" +  Math.floor(Math.random() * (100 - 1 + 1)) + 1;
That's not dark mode, is this already added with the poll MR? :)

2025-02-17 16:18 UTC, LukasBSI commented
Changelog entry is still missing :)

2025-02-20 10:32 UTC, LukasBSI commented on CHANGELOG.md
> +* Add dark mode
```suggestion
* Add dark mode support for general layout and all elements
```

2025-02-20 10:32 UTC, LukasBSI approved these changes

2025-02-20 10:33 UTC, merged

2025-02-20 10:45 UTC, antoninodelfiume commented on CHANGELOG.md
> +* Add dark mode
changed